# Generated by Django 5.0.6 on 2024-07-12 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_remove_listings_bids_remove_comments_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
