# Generated by Django 5.0.6 on 2024-07-12 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
